jobs:
  label-linter:
    if: github.event.pull_request.merged == true
    name: Audit Labels
    permissions:
      contents: read
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
      with:
        sparse-checkout: .github/allowed-labels.yml
        sparse-checkout-cone-mode: false
    - continue-on-error: true
      if: success()
      name: Audit Labels
      uses: crazy-max/ghaction-github-labeler@v4
      with:
        dry-run: false
        github-token: ${{ secrets.GITHUB_TOKEN }}
        skip-delete: true
        yaml-file: .github/allowed-labels.yml
name: Audit Labels
on:
  repository_dispatch:
    types: trigger-ga___label-auditor.yml
