jobs:
  auto-labeler:
    name: Auto Labeler
    permissions:
      contents: read
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Add Labels
      uses: actions/labeler@v4
      with:
        configuration-path: .github/label-ruleset.yml
        repo-token: ${{ secrets.GITHUB_TOKEN }}
name: Auto Labeler
on:
  repository_dispatch:
    types: trigger-ga___label-auto-language.yml
