jobs:
  check_oncall_labels:
    name: Check On Call Review labels
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: docker://agilepathway/pull-request-label-checker:latest
      with:
        all_of: On Call Review complete
        none_of: On Call Review needed
        repo_token: ${{ secrets.GITHUB_TOKEN }}
  check_stats_labels:
    name: Check Stats labels
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: docker://agilepathway/pull-request-label-checker:latest
      with:
        one_of: Application,MVP,Workflow,Task,Bug
        repo_token: ${{ secrets.GITHUB_TOKEN }}
name: Label Checker
on:
  repository_dispatch:
    types: trigger-ga___label-checker.yml
