jobs:
  phpcs:
    name: PHP Linter
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - continue-on-error: true
      id: changed-files
      name: Get changed files
      uses: tj-actions/changed-files@v41
      with:
        files: /php/**/*.php
    - continue-on-error: true
      if: steps.changed-files.outputs.any_changed == 'true'
      name: Install PHP_CodeSniffer
      run: 'curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar

        php phpcs.phar --version

        '
    - continue-on-error: true
      if: steps.changed-files.outputs.any_changed == 'true'
      name: Run PHPCS
      uses: thenabeel/action-phpcs@v8
      with:
        files: '**.php'
        phpcs_path: php phpcs.phar
        standard: .github/linters/phpcs.xml
name: PHP Linter
on:
  repository_dispatch:
    types: trigger-ga___lint-php.yml
