jobs:
  rubocop:
    name: RuboCop
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repository
      uses: actions/checkout@v2
    - continue-on-error: true
      id: changed-files
      name: Get changed files
      uses: tj-actions/changed-files@v41
      with:
        files: ruby/**/*.rb
    - continue-on-error: true
      name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
    - continue-on-error: true
      name: Install dependencies
      run: 'gem install rubocop

        '
    - continue-on-error: true
      if: steps.changed-files.outputs.any_changed == 'true'
      name: Run RuboCop
      run: "changed_files=(${{steps.changed-files.outputs.all_changed_files}})\nrubocop\
        \ --config .github/linters/.ruby-lint.yml \"${changed_files[@]}\"     \n"
name: Ruby Linting
on:
  repository_dispatch:
    types: trigger-ga___lint-ruby.yml
