jobs:
  golangci:
    name: Lint GoLang
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout files
      uses: actions/checkout@v3
      with:
        sparse-checkout: '.github

          gov2

          '
    - continue-on-error: true
      id: changed-files
      name: Get changed files
      uses: tj-actions/changed-files@v41
      with:
        files: gov2/**/*.go
    - continue-on-error: true
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - continue-on-error: true
      if: steps.changed-files.outputs.any_changed == 'true'
      name: install golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh
        | sh -s -- -b $(go env GOPATH)/bin v1.47.3
    - continue-on-error: true
      if: steps.changed-files.outputs.any_changed == 'true'
      name: run golangci-lint
      run: 'cd gov2

        ./lint_all_go.sh

        '
name: Lint GoLang
on:
  repository_dispatch:
    types: trigger-ga___lint-golang.yml
permissions:
  contents: read
