jobs:
  check:
    name: Lint Rust
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout files
      uses: actions/checkout@v4
      with:
        sparse-checkout: '.github

          rustv1

          '
    - continue-on-error: true
      id: changed-files
      name: Get changed files
      uses: tj-actions/changed-files@v41
      with:
        files: rustv1/**/*.{rs,toml}
    - continue-on-error: true
      if: steps.changed-files.outputs.any_changed == 'true'
      name: setup
      run: sudo apt-get update && sudo apt-get install -y libclang-dev
    - continue-on-error: true
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt
        toolchain: 1.76.0
    - continue-on-error: true
      if: steps.changed-files.outputs.any_changed == 'true'
      name: Set Environment
      run: 'export RUSTFLAGS="-D warnings" ; export APP_ENVIRONMENT="test"

        '
    - continue-on-error: true
      if: steps.changed-files.outputs.any_changed == 'true'
      name: Rust format
      run: '"$HOME/.cargo/bin/cargo" fmt --manifest-path rustv1/cross_service/Cargo.toml
        --all --check && "$HOME/.cargo/bin/cargo" fmt --manifest-path rustv1/examples/Cargo.toml
        --all --check && "$HOME/.cargo/bin/cargo" fmt --manifest-path rustv1/lambda/Cargo.toml
        --all --check && "$HOME/.cargo/bin/cargo" fmt --manifest-path rustv1/webassembly/Cargo.toml
        --all --check

        '
    - continue-on-error: true
      if: steps.changed-files.outputs.any_changed == 'true' && (success() || failure())
      name: Rust lint
      run: '"$HOME/.cargo/bin/cargo" clippy --manifest-path rustv1/cross_service/Cargo.toml
        --all && "$HOME/.cargo/bin/cargo" clippy --manifest-path rustv1/examples/Cargo.toml
        --all && "$HOME/.cargo/bin/cargo" clippy --manifest-path rustv1/lambda/Cargo.toml
        --all && "$HOME/.cargo/bin/cargo" clippy --manifest-path rustv1/webassembly/Cargo.toml
        --all

        '
    - continue-on-error: true
      if: steps.changed-files.outputs.any_changed == 'true'
      name: Rust test
      run: '"$HOME/.cargo/bin/cargo" test --manifest-path rustv1/cross_service/Cargo.toml
        --all && "$HOME/.cargo/bin/cargo" test --manifest-path rustv1/examples/Cargo.toml
        --all && "$HOME/.cargo/bin/cargo" test --manifest-path rustv1/lambda/Cargo.toml
        --all && "$HOME/.cargo/bin/cargo" test --manifest-path rustv1/webassembly/Cargo.toml
        --all

        '
name: Lint - Test - Format Rust
on:
  repository_dispatch:
    types: trigger-ga___lint-rust.yml
permissions:
  contents: read
