jobs:
  validate-doc-metadata:
    name: Validate Doc Metadata
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: checkout repo content
      uses: actions/checkout@v4
    - continue-on-error: true
      name: validate metadata
      uses: awsdocs/aws-doc-sdk-examples-tools@2024-06-10-A
      with:
        doc_gen_only: 'False'
        strict_titles: 'True'
name: Validate Documentation Metadata
on:
  repository_dispatch:
    types: trigger-ga___validate-doc-metadata.yml
